/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.reviewdialog;

import android.content.pm.PackageManager;
import android.graphics.drawable.Drawable;

import com.codemybrainsout.ratingdialog.RatingDialog;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.util.TiFileHelper;
import org.appcelerator.titanium.util.TiUrl;

@Kroll.module(name="TitaniumReviewDialog", id="ti.reviewdialog")
public class TitaniumReviewDialogModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TitaniumReviewDialogModule";
	private static final boolean DBG = TiConfig.LOGD;

	// Methods
	@Kroll.method
	public void requestReview(KrollDict configuration) throws PackageManager.NameNotFoundException {
		KrollFunction callback = (KrollFunction) configuration.get("onFeedback");
		String storeURL = configuration.getString("storeURL");
		String icon = configuration.getString("icon");

		Drawable appIcon = appIcon = TiApplication.getAppRootOrCurrentActivity()
				.getApplication()
				.getPackageManager()
				.getApplicationIcon(TiApplication.getInstance().getAppInfo().getId());

		// Configure the base rating dialog
		RatingDialog.Builder ratingDialogBuilder = new RatingDialog.Builder(TiApplication.getAppCurrentActivity())
				.threshold(4)
				.session(1)
				.icon(appIcon)
				.onRatingBarFormSumbit(feedback -> {
					KrollDict event = new KrollDict();
					event.put("value", feedback);

					if (callback != null) {
						callback.callAsync(getKrollObject(), event);
					}
				});

		// Set store URL if available
		if (storeURL != null) {
			ratingDialogBuilder = ratingDialogBuilder.playstoreUrl(storeURL);
		}

		// Set custom icon if available
		if (icon != null) {
			TiUrl iconUrl = new TiUrl(icon);
			TiFileHelper fileHelper = new TiFileHelper(TiApplication.getInstance());
			Drawable iconDrawable = fileHelper.loadDrawable(iconUrl.resolve(), false);

			if (iconDrawable != null) {
				ratingDialogBuilder = ratingDialogBuilder.icon(iconDrawable);
			}
		}

		// Show the dialog
		RatingDialog ratingDialog = ratingDialogBuilder.build();

		// Perform some custom overrides
		ratingDialog.setCancelable(true);

		ratingDialog.show();
	}

	@Kroll.method
	public boolean isSupported() {
		return true; // Always supported on Android, keeping for parity with iOS
	}
}

